apiVersion: v1
kind: Namespace
metadata:
  name: scheduling-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod
  namespace: scheduling-ns
spec:
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
            - node-name-target
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
