apiVersion: v1
kind: Namespace
metadata:
  name: multi-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: multi-ns
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: writer
    image: busybox
    command: ["sh", "-c", "while true; do date >> /data/index.html; sleep 5; done"]
    volumeMounts:
    - name: shared-data
      mountPath: /data
