apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-welcome
  namespace: gateway-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-welcome
  template:
    metadata:
      labels:
        app: nginx-welcome
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: welcome-page
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: welcome-page
        configMap:
          name: nginx-welcome-page
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-welcome-page
  namespace: gateway-ns
data:
  index.html: |
    <html>
      <head><title>Welcome</title></head>
      <body>
        <h1>Welcome to Gateway</h1>
      </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-welcome
  namespace: gateway-ns
spec:
  selector:
    app: nginx-welcome
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNJVENDQWNlZ0F3SUJBZ0lVYlVrQmJ5TzEvTGp0S0JQRS9RSFBOVWZEVmUwd0NnWUlLb1pJemowRUF3SXcKVERFTE1Ba0dBMVVFQmhNQ1ZWTXhDekFKQmdOVkJBZ1RBa05CTVJZd0ZBWURWUVFIRXcxVFlXNGdSbkpoYm1OcApjMk52TVJnd0ZnWURWUVFERXc5dGVXZGhkR1YzWVhrdWJHOWpZV3d3SGhjTk1qVXhNVEF4TVRNek9UQXdXaGNOCk1qWXhNVEF4TVRNek9UQXdXakJNTVFzd0NRWURWUVFHRXdKVlV6RUxNQWtHQTFVRUNCTUNRMEV4RmpBVUJnTlYKQkFjVERWTmhiaUJHY21GdVkybHpZMjh4R0RBV0JnTlZCQU1URDIxNVoyRjBaWGRoZVM1c2IyTmhiREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkhWZjVJVW11VkJ5dGZqL0V1RWdocEtjNlUvY0MrK3I2SElUClFSa2NEWk8yaG16TWh4RFhHSGZyd1NmaUx0dENoT1JJMno3ZUladFRuTk45UlBoZ1MrdWpnWVl3Z1lNd0RnWUQKVlIwUEFRSC9CQVFEQWdXZ01CTUdBMVVkSlFRTU1Bb0dDQ3NHQVFVRkJ3TUJNQXdHQTFVZEV3RUIvd1FDTUFBdwpIUVlEVlIwT0JCWUVGSXJTYVIzWGdLNUdVSmp6Ulp5ZjByQWNhTUJMTUM4R0ExVWRFUVFvTUNhQ0QyMTVaMkYwClpYZGhlUzVzYjJOaGJJSVRkM2QzTG0xNVoyRjBaWGRoZVM1c2IyTmhiREFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlBNUt0MWhqaHk0MlhiSTlCcStjVlRJR3dFZTBmQWJ2MzdJc1ppVnBtMnl6QUloQU1rRHBJbzRxU2hKUjE5bAp4a0V1Z3pVei9IZy9VbkRBbDcvS2xndkZmdGU1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUFtR0VjMTU4MHNxazZtdDJ6cnYzZUJ0SUZZbHNBeGFFZHM5ZGlKQ0R4d2xvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFZFYva2hTYTVVSEsxK1A4UzRTQ0drcHpwVDl3TDc2dm9jaE5CR1J3Tms3YUdiTXlIRU5jWQpkK3ZCSitJdTIwS0U1RWpiUHQ0aG0xT2MwMzFFK0dCTDZ3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: ingress-web
  namespace: gateway-ns
type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  namespace: gateway-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: mygateway.local 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-welcome 
            port:
              number: 80
  tls:
  - hosts:
      - mygateway.local
    secretName: ingress-web
