apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rbac
  name: rbac
  namespace: rbac-ns
spec:
  containers:
  - image: nginx:alpine
    name: rbac
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
