apiVersion: v1
kind: Namespace
metadata:
  name: crd-ns
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myapps.example.com
spec:
  group: example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              size:
                type: integer
  scope: Namespaced
  names:
    plural: myapps
    singular: myapp
    kind: MyApp
    shortNames:
    - ma
---
apiVersion: example.com/v1
kind: MyApp
metadata:
  name: example-myapp
  namespace: crd-ns
spec:
  size: 3
